version: '3.7'

services:
  web:
    container_name: ${CONTAINER_NAME}
    image: ${DOCKER_REGISTRY_HOST}/sale_website/web:develop
    ports:
      - ${CONTAINER_PORT}:80
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
