import { ROUTE } from '~/modules/mmsx/routes/config'

const REDIRECT_NOTIFICATION = {
  DEVICE_REQUEST_DETAIL: 0,
  DEVICE_ASSIGN_DETAIL: 1,
  JOB_LIST: 2,
  JOB_DETAIL: 3,
  REPAIR_REQUEST_DETAIL: 4,
  WARNING_SYSTEM: 5,
}
export const config = {
  [REDIRECT_NOTIFICATION.DEVICE_REQUEST_DETAIL]:
    ROUTE.REQUEST_DEVICE.DETAIL.PATH,
  [REDIRECT_NOTIFICATION.DEVICE_ASSIGN_DETAIL]: ROUTE.DEVICE_ASSIGN.DETAIL.PATH,
  [REDIRECT_NOTIFICATION.JOB_LIST]: ROUTE.JOB.LIST.PATH,
  [REDIRECT_NOTIFICATION.REPAIR_REQUEST_DETAIL]:
    ROUTE.REPAIR_REQUEST.DETAIL.PATH,
  [REDIRECT_NOTIFICATION.JOB_DETAIL]: ROUTE.JOB.DETAIL.PATH,
  [REDIRECT_NOTIFICATION.WARNING_SYSTEM]: ROUTE.WARNING_SYSTEM.LIST.PATH,
}
