export const FUNCTION_CODE = {
  // ACCREDITATION_TEMPLATE_GROUP
  CREATE_ACCREDITATION_TEMPLATE: 'MMS_CREATE_ACCREDITATION_TEMPLATE',
  LIST_ACCREDITATION_TEMPLATE: 'MMS_LIST_ACCREDITATION_TEMPLATE',
  DETAIL_ACCREDITATION_TEMPLATE: 'MMS_DETAIL_ACCREDITATION_TEMPLATE',
  UPDATE_ACCREDITATION_TEMPLATE: 'MMS_UPDATE_ACCREDITATION_TEMPLATE',
  UPDATE_STATUS_ACCREDITATION_TEMPLATE:
    'MMS_UPDATE_STATUS_ACCREDITATION_TEMPLATE',
  IMPORT_ACCREDITATION_TEMPLATE: 'MMS_IMPORT_ACCREDITATION_TEMPLATE',
  EXPORT_ACCREDITATION_TEMPLATE: 'MMS_EXPORT_ACCREDITATION_TEMPLATE',

  // AREA_GROUP
  CREATE_AREA: 'MMS_CREATE_AREA',
  LIST_AREA: 'MMS_LIST_AREA',
  DETAIL_AREA: 'MMS_DETAIL_AREA',
  UPDATE_AREA: 'MMS_UPDATE_AREA',
  UPDATE_STATUS_AREA: 'MMS_UPDATE_STATUS_AREA',
  IMPORT_AREA: 'MMS_IMPORT_AREA',
  EXPORT_AREA: 'MMS_EXPORT_AREA',

  // OPERATION_INDEX_GROUP
  CREATE_OPERATION_INDEX: 'MMS_CREATE_OPERATION_INDEX',
  LIST_OPERATION_INDEX: 'MMS_LIST_OPERATION_INDEX',
  DETAIL_OPERATION_INDEX: 'MMS_DETAIL_OPERATION_INDEX',
  UPDATE_OPERATION_INDEX: 'MMS_UPDATE_OPERATION_INDEX',
  UPDATE_STATUS_OPERATION_INDEX: 'MMS_UPDATE_STATUS_OPERATION_INDEX',
  DELETE_OPERATION_INDEX: 'MMS_DELETE_OPERATION_INDEX',

  // ARTICLE_DEVICE_GROUP_GROUP
  CREATE_ARTICLE_DEVICE_GROUP: 'MMS_CREATE_ARTICLE_DEVICE_GROUP',
  UPDATE_ARTICLE_DEVICE_GROUP: 'MMS_UPDATE_ARTICLE_DEVICE_GROUP',
  DETAIL_ARTICLE_DEVICE_GROUP: 'MMS_DETAIL_ARTICLE_DEVICE_GROUP',
  LIST_ARTICLE_DEVICE_GROUP: 'MMS_LIST_ARTICLE_DEVICE_GROUP',
  UPDATE_STATUS_ARTICLE_DEVICE_GROUP: 'MMS_UPDATE_STATUS_ARTICLE_DEVICE_GROUP',
  IMPORT_ARTICLE_DEVICE_GROUP: 'MMS_IMPORT_ARTICLE_DEVICE_GROUP',
  EXPORT_ARTICLE_DEVICE_GROUP: 'MMS_EXPORT_ARTICLE_DEVICE_GROUP',

  // ATTRIBUTE_TYPE_GROUP
  CREATE_ATTRIBUTE_TYPE: 'MMS_CREATE_ATTRIBUTE_TYPE',
  LIST_ATTRIBUTE_TYPE: 'MMS_LIST_ATTRIBUTE_TYPE',
  DETAIL_ATTRIBUTE_TYPE: 'MMS_DETAIL_ATTRIBUTE_TYPE',
  UPDATE_ATTRIBUTE_TYPE: 'MMS_UPDATE_ATTRIBUTE_TYPE',
  UPDATE_STATUS_ATTRIBUTE_TYPE: 'MMS_UPDATE_STATUS_ATTRIBUTE_TYPE',
  IMPORT_ATTRIBUTE_TYPE: 'MMS_IMPORT_ATTRIBUTE_TYPE',
  EXPORT_ATTRIBUTE_TYPE: 'MMS_EXPORT_ATTRIBUTE_TYPE',

  // CHECKLIST_TEMPLATE_GROUP
  CREATE_CHECKLIST_TEMPLATE: 'MMS_CREATE_CHECKLIST_TEMPLATE',
  LIST_CHECKLIST_TEMPLATE: 'MMS_LIST_CHECKLIST_TEMPLATE',
  DETAIL_CHECKLIST_TEMPLATE: 'MMS_DETAIL_CHECKLIST_TEMPLATE',
  UPDATE_CHECKLIST_TEMPLATE: 'MMS_UPDATE_CHECKLIST_TEMPLATE',
  UPDATE_STATUS_CHECKLIST_TEMPLATE: 'MMS_UPDATE_STATUS_CHECKLIST_TEMPLATE',
  IMPORT_CHECKLIST_TEMPLATE: 'MMS_IMPORT_CHECKLIST_TEMPLATE',
  EXPORT_CHECKLIST_TEMPLATE: 'MMS_EXPORT_CHECKLIST_TEMPLATE',

  // DEVICE_ASSIGNMENT_GROUP
  CREATE_DEVICE_ASSIGNMENT: 'MMS_CREATE_DEVICE_ASSIGNMENT',
  UPDATE_DEVICE_ASSIGNMENT: 'MMS_UPDATE_DEVICE_ASSIGNMENT',
  DELETE_DEVICE_ASSIGNMENT: 'MMS_DELETE_DEVICE_ASSIGNMENT',
  DETAIL_DEVICE_ASSIGNMENT: 'MMS_DETAIL_DEVICE_ASSIGNMENT',
  LIST_DEVICE_ASSIGNMENT: 'MMS_LIST_DEVICE_ASSIGNMENT',
  GENERATE_QR_CODE_SERIAL_DEVICE_ASSIGNMENT:
    'MMS_GENERATE_QR_CODE_SERIAL_DEVICE_ASSIGNMENT',
  UPDATE_STATUS_DEVICE_ASSIGNMENT: 'MMS_UPDATE_STATUS_DEVICE_ASSIGNMENT',

  // DEVICE_GROUP_GROUP
  CREATE_DEVICE_GROUP: 'MMS_CREATE_DEVICE_GROUP',
  UPDATE_DEVICE_GROUP: 'MMS_UPDATE_DEVICE_GROUP',
  UPDATE_STATUS_DEVICE_GROUP: 'MMS_UPDATE_STATUS_DEVICE_GROUP',
  DETAIL_DEVICE_GROUP: 'MMS_DETAIL_DEVICE_GROUP',
  LIST_DEVICE_GROUP: 'MMS_LIST_DEVICE_GROUP',
  STOCK_QUANTITY_DEVICE_GROUP: 'MMS_STOCK_QUANTITY_DEVICE_GROUP',
  IMPORT_DEVICE_GROUP: 'MMS_IMPORT_DEVICE_GROUP',
  EXPORT_DEVICE_GROUP: 'MMS_EXPORT_DEVICE_GROUP',

  // DEVICE_REQUEST
  CREATE_DEVICE_REQUEST_TICKET: 'MMS_CREATE_DEVICE_REQUEST_TICKET',
  CREATE_GRANT_DEVICE_REQUEST_TICKET: 'MMS_CREATE_GRANT_DEVICE_REQUEST_TICKET',
  CREATE_RETURN_DEVICE_REQUEST_TICKET:
    'MMS_CREATE_RETURN_DEVICE_REQUEST_TICKET',
  DETAIL_DEVICE_REQUEST_TICKET: 'MMS_DETAIL_DEVICE_REQUEST_TICKET',
  UPDATE_DEVICE_REQUEST_TICKET: 'MMS_UPDATE_DEVICE_REQUEST_TICKET',
  DELETE_DEVICE_REQUEST_TICKET: 'MMS_DELETE_DEVICE_REQUEST_TICKET',
  LIST_DEVICE_REQUEST: 'MMS_LIST_DEVICE_REQUEST',
  CONFIRM_DEVICE_REQUEST: 'MMS_CONFIRM_DEVICE_REQUEST',

  // DEVICE_STATUS_GROUP
  CREATE_DEVICE_STATUS: 'MMS_CREATE_DEVICE_STATUS',
  UPDATE_DEVICE_STATUS: 'MMS_UPDATE_DEVICE_STATUS',
  DELETE_DEVICE_STATUS: 'MMS_DELETE_DEVICE_STATUS',
  DETAIL_DEVICE_STATUS: 'MMS_DETAIL_DEVICE_STATUS',
  LIST_DEVICE_STATUS: 'MMS_LIST_DEVICE_STATUS',

  // DEVICE_TYPE_GROUP
  CREATE_DEVICE_TYPE: 'MMS_CREATE_DEVICE_TYPE',
  LIST_DEVICE_TYPE: 'MMS_LIST_DEVICE_TYPE',
  DETAIL_DEVICE_TYPE: 'MMS_DETAIL_DEVICE_TYPE',
  UPDATE_DEVICE_TYPE: 'MMS_UPDATE_DEVICE_TYPE',
  UPDATE_STATUS_DEVICE_TYPE: 'MMS_UPDATE_STATUS_DEVICE_TYPE',
  IMPORT_DEVICE_TYPE: 'MMS_IMPORT_DEVICE_TYPE',
  EXPORT_DEVICE_TYPE: 'MMS_EXPORT_DEVICE_TYPE',

  // DEVICE_NAME_GROUP
  CREATE_DEVICE_NAME: 'MMS_CREATE_DEVICE_NAME',
  LIST_DEVICE_NAME: 'MMS_LIST_DEVICE_NAME',
  DETAIL_DEVICE_NAME: 'MMS_DETAIL_DEVICE_NAME',
  UPDATE_DEVICE_NAME: 'MMS_UPDATE_DEVICE_NAME',
  UPDATE_STATUS_DEVICE_NAME: 'MMS_UPDATE_STATUS_DEVICE_NAME',
  IMPORT_DEVICE_NAME: 'MMS_IMPORT_DEVICE_NAME',
  EXPORT_DEVICE_NAME: 'MMS_EXPORT_DEVICE_NAME',

  // DEVICE_GROUP
  CREATE_DEVICE: 'MMS_CREATE_DEVICE',
  UPDATE_DEVICE: 'MMS_UPDATE_DEVICE',
  DELETE_DEVICE: 'MMS_DELETE_DEVICE',
  DETAIL_DEVICE: 'MMS_DETAIL_DEVICE',
  LIST_DEVICE: 'MMS_LIST_DEVICE',
  LIST_SUPPLY_BY_DEVICE: 'MMS_LIST_SUPPLY_BY_DEVICE',
  IMPORT_DEVICE: 'MMS_IMPORT_DEVICE',
  EXPORT_DEVICE: 'MMS_EXPORT_DEVICE',
  CONFIRM_DEVICE: 'MMS_CONFIRM_DEVICE',
  UPDATE_STATUS_DEVICE: 'MMS_UPDATE_STATUS_DEVICE',
  UPDATE_LOCATION_DEVICE: 'MMS_UPDATE_LOCATION_DEVICE',
  HISTORY_ACTIVITY_DEVICE: 'MMS_HISTORY_ACTIVITY_DEVICE',
  UPDATE_ACTUAL_SERIAL_DEVICE: 'MMS_UPDATE_ACTUAL_SERIAL_DEVICE',
  // ERROR_TYPE_GROUP
  CREATE_ERROR_TYPE: 'MMS_CREATE_ERROR_TYPE',
  LIST_ERROR_TYPE: 'MMS_LIST_ERROR_TYPE',
  DETAIL_ERROR_TYPE: 'MMS_DETAIL_ERROR_TYPE',
  UPDATE_ERROR_TYPE: 'MMS_UPDATE_ERROR_TYPE',
  UPDATE_STATUS_ERROR_TYPE: 'MMS_UPDATE_STATUS_ERROR_TYPE',
  DELETE_ERROR_TYPE: 'MMS_DELETE_ERROR_TYPE',
  IMPORT_ERROR_TYPE: 'MMS_IMPORT_ERROR_TYPE',
  EXPORT_ERROR_TYPE: 'MMS_EXPORT_ERROR_TYPE',

  // INSTALLATION_TEMPLATE_GROUP
  CREATE_INSTALLATION_TEMPLATE: 'MMS_CREATE_INSTALLATION_TEMPLATE',
  LIST_INSTALLATION_TEMPLATE: 'MMS_LIST_INSTALLATION_TEMPLATE',
  DETAIL_INSTALLATION_TEMPLATE: 'MMS_DETAIL_INSTALLATION_TEMPLATE',
  UPDATE_INSTALLATION_TEMPLATE: 'MMS_UPDATE_INSTALLATION_TEMPLATE',
  UPDATE_STATUS_INSTALLATION_TEMPLATE:
    'MMS_UPDATE_STATUS_INSTALLATION_TEMPLATE',
  IMPORT_INSTALLATION_TEMPLATE: 'MMS_IMPORT_INSTALLATION_TEMPLATE',
  EXPORT_INSTALLATION_TEMPLATE: 'MMS_EXPORT_INSTALLATION_TEMPLATE',

  // JOB_GROUP
  LIST_JOB: 'MMS_LIST_JOB',
  ASSIGNMENT_JOB: 'MMS_ASSIGNMENT_JOB',
  UPDATE_STATUS_JOB: 'MMS_UPDATE_STATUS_JOB',
  EXECUTE_JOB: 'MMS_EXECUTE_JOB',
  APPROVE_JOB: 'MMS_APPROVE_JOB',
  DETAIL_JOB: 'MMS_DETAIL_JOB',
  UPDATE_JOB: 'MMS_UPDATE_JOB',
  LIST_SUPPLY_BY_JOB: 'MMS_LIST_SUPPLY_BY_JOB',

  // MAINTENANCE_ATTRIBUTE_GROUP
  CREATE_MAINTENANCE_ATTRIBUTE: 'MMS_CREATE_MAINTENANCE_ATTRIBUTE',
  UPDATE_MAINTENANCE_ATTRIBUTE: 'MMS_UPDATE_MAINTENANCE_ATTRIBUTE',
  UPDATE_STATUS_MAINTENANCE_ATTRIBUTE:
    'MMS_UPDATE_STATUS_MAINTENANCE_ATTRIBUTE',
  DETAIL_MAINTENANCE_ATTRIBUTE: 'MMS_DETAIL_MAINTENANCE_ATTRIBUTE',
  LIST_MAINTENANCE_ATTRIBUTE: 'MMS_LIST_MAINTENANCE_ATTRIBUTE',

  // MAINTENANCE_TEAM_GROUP
  CREATE_MAINTENANCE_TEAM: 'MMS_CREATE_MAINTENANCE_TEAM',
  UPDATE_MAINTENANCE_TEAM: 'MMS_UPDATE_MAINTENANCE_TEAM',
  UPDATE_STATUS_MAINTENANCE_TEAM: 'MMS_UPDATE_STATUS_MAINTENANCE_TEAM',
  DELETE_MAINTENANCE_TEAM: 'MMS_DELETE_MAINTENANCE_TEAM',
  DETAIL_MAINTENANCE_TEAM: 'MMS_DETAIL_MAINTENANCE_TEAM',
  LIST_MAINTENANCE_TEAM: 'MMS_LIST_MAINTENANCE_TEAM',
  LIST_MEMBER_OF_MAINTENANCE_TEAM: 'MMS_LIST_MEMBER_OF_MAINTENANCE_TEAM',
  LIST_MAINTENANCE_TEAM_BY_USER: 'MMS_LIST_MAINTENANCE_TEAM_BY_USER',
  LIST_MAINTENANCE_TEAM_AND_USER: 'MMS_LIST_MAINTENANCE_TEAM_AND_USER',

  // MAINTENANCE_TEMPLATE_GROUP
  CREATE_MAINTENANCE_TEMPLATE: 'MMS_CREATE_MAINTENANCE_TEMPLATE',
  LIST_MAINTENANCE_TEMPLATE: 'MMS_LIST_MAINTENANCE_TEMPLATE',
  DETAIL_MAINTENANCE_TEMPLATE: 'MMS_DETAIL_MAINTENANCE_TEMPLATE',
  UPDATE_MAINTENANCE_TEMPLATE: 'MMS_UPDATE_MAINTENANCE_TEMPLATE',
  UPDATE_STATUS_MAINTENANCE_TEMPLATE: 'MMS_UPDATE_STATUS_MAINTENANCE_TEMPLATE',
  IMPORT_MAINTENANCE_TEMPLATE: 'MMS_IMPORT_MAINTENANCE_TEMPLATE',
  EXPORT_MAINTENANCE_TEMPLATE: 'MMS_EXPORT_MAINTENANCE_TEMPLATE',

  // PLAN_GROUP
  CREATE_PLAN: 'MMS_CREATE_PLAN',
  UPDATE_PLAN: 'MMS_UPDATE_PLAN',
  DELETE_PLAN: 'MMS_DELETE_PLAN',
  DETAIL_PLAN: 'MMS_DETAIL_PLAN',
  LIST_PLAN: 'MMS_LIST_PLAN',
  CONFIRM_PLAN: 'MMS_CONFIRM_PLAN',
  GANTT_CHART_PLAN: 'MMS_GANTT_CHART_PLAN',
  GENERATE_JOB_FOR_PLAN: 'MMS_GENERATE_JOB_FOR_PLAN',
  UPDATE_STATUS_PLAN: 'MMS_UPDATE_STATUS_PLAN',
  EXPORT_PLAN: 'MMS_EXPORT_PLAN',

  // MAINTENANCE_PLAN_GROUP
  CREATE_MAINTENANCE_PLAN: 'MMS_CREATE_MAINTENANCE_PLAN',
  UPDATE_MAINTENANCE_PLAN: 'MMS_UPDATE_MAINTENANCE_PLAN',
  UPDATE_STATUS_MAINTENANCE_PLAN: 'MMS_UPDATE_STATUS_MAINTENANCE_PLAN',
  DETAIL_MAINTENANCE_PLAN: 'MMS_DETAIL_MAINTENANCE_PLAN',
  DELETE_MAINTENANCE_PLAN: 'MMS_DELETE_MAINTENANCE_PLAN',
  LIST_MAINTENANCE_PLAN: 'MMS_LIST_MAINTENANCE_PLAN',
  IMPORT_MAINTENANCE_PLAN: 'MMS_IMPORT_MAINTENANCE_PLAN',
  EXPORT_MAINTENANCE_PLAN: 'MMS_EXPORT_MAINTENANCE_PLAN',

  // REPAIR_REQUEST_GROUP
  CREATE_REPAIR_REQUEST: 'MMS_CREATE_REPAIR_REQUEST',
  UPDATE_REPAIR_REQUEST: 'MMS_UPDATE_REPAIR_REQUEST',
  UPDATE_STATUS_REPAIR_REQUEST: 'MMS_UPDATE_STATUS_REPAIR_REQUEST',
  DETAIL_REPAIR_REQUEST: 'MMS_DETAIL_REPAIR_REQUEST',
  LIST_REPAIR_REQUEST: 'MMS_LIST_REPAIR_REQUEST',
  IMPORT_REPAIR_REQUEST: 'MMS_IMPORT_REPAIR_REQUEST',
  EXPORT_REPAIR_REQUEST: 'MMS_EXPORT_REPAIR_REQUEST',

  // DEVICE_STATUS_GROUP
  LIST_DEVICE_STATUS_BY_SERIAL: 'MMS_LIST_DEVICE_STATUS_BY_SERIAL',

  REPORT_GROUP: 'MMS_REPORT_GROUP',
  VIEW_REPORT: 'MMS_VIEW_REPORT',

  // SUPPLY_GROUP_GROUP
  CREATE_SUPPLY_GROUP: 'MMS_CREATE_SUPPLY_GROUP',
  UPDATE_SUPPLY_GROUP: 'MMS_UPDATE_SUPPLY_GROUP',
  UPDATE_STATUS_SUPPLY_GROUP: 'MMS_UPDATE_STATUS_SUPPLY_GROUP',
  DETAIL_SUPPLY_GROUP: 'MMS_DETAIL_SUPPLY_GROUP',
  LIST_SUPPLY_GROUP: 'MMS_LIST_SUPPLY_GROUP',
  IMPORT_SUPPLY_GROUP: 'MMS_IMPORT_SUPPLY_GROUP',
  EXPORT_SUPPLY_GROUP: 'MMS_EXPORT_SUPPLY_GROUP',

  // SUPPLY_REQUEST
  CREATE_SUPPLY_REQUEST_TICKET: 'MMS_CREATE_SUPPLY_REQUEST_TICKET',
  DETAIL_SUPPLY_REQUEST_TICKET: 'MMS_DETAIL_SUPPLY_REQUEST_TICKET',
  UPDATE_SUPPLY_REQUEST_TICKET: 'MMS_UPDATE_SUPPLY_REQUEST_TICKET',
  DELETE_SUPPLY_REQUEST_TICKET: 'MMS_DELETE_SUPPLY_REQUEST_TICKET',
  LIST_SUPPLY_REQUEST: 'MMS_LIST_SUPPLY_REQUEST',
  CONFIRM_SUPPLY_REQUEST_TICKET: 'MMS_CONFIRM_SUPPLY_REQUEST_TICKET',

  // SUPPLY_GROUP
  CREATE_SUPPLY: 'MMS_CREATE_SUPPLY',
  UPDATE_SUPPLY: 'MMS_UPDATE_SUPPLY',
  UPDATE_STATUS_SUPPLY: 'MMS_UPDATE_STATUS_SUPPLY',
  DETAIL_SUPPLY: 'MMS_DETAIL_SUPPLY',
  LIST_SUPPLY: 'MMS_LIST_SUPPLY',
  IMPORT_SUPPLY: 'MMS_IMPORT_SUPPLY',
  EXPORT_SUPPLY: 'MMS_EXPORT_SUPPLY',

  // TRANSFER_REQUEST
  CREATE_TRANSFER_REQUEST: 'MMS_CREATE_TRANSFER_REQUEST',
  DETAIL_TRANSFER_REQUEST: 'MMS_DETAIL_TRANSFER_REQUEST',
  UPDATE_TRANSFER_REQUEST: 'MMS_UPDATE_TRANSFER_REQUEST',
  DELETE_TRANSFER_REQUEST: 'MMS_DELETE_TRANSFER_REQUEST',
  LIST_TRANSFER_REQUEST: 'MMS_LIST_TRANSFER_REQUEST',
  CONFIRM_TRANSFER_REQUEST: 'MMS_CONFIRM_TRANSFER_REQUEST',

  // TRANSFER_TICKET
  CREATE_TRANSFER_TICKET: 'MMS_CREATE_TRANSFER_TICKET',
  DETAIL_TRANSFER_TICKET: 'MMS_DETAIL_TRANSFER_TICKET',
  UPDATE_TRANSFER_TICKET: 'MMS_UPDATE_TRANSFER_TICKET',
  DELETE_TRANSFER_TICKET: 'MMS_DELETE_TRANSFER_TICKET',
  LIST_TRANSFER_TICKET: 'MMS_LIST_TRANSFER_TICKET',
  CONFIRM_TRANSFER_TICKET: 'MMS_CONFIRM_TRANSFER_TICKET',

  // UNIT_GROUP
  CREATE_UNIT: 'MMS_CREATE_UNIT',
  LIST_UNIT: 'MMS_LIST_UNIT',
  DETAIL_UNIT: 'MMS_DETAIL_UNIT',
  UPDATE_UNIT: 'MMS_UPDATE_UNIT',
  UPDATE_STATUS_UNIT: 'MMS_UPDATE_STATUS_UNIT',
  IMPORT_UNIT: 'MMS_IMPORT_UNIT',
  EXPORT_UNIT: 'MMS_EXPORT_UNIT',

  // VENDOR_GROUP
  CREATE_VENDOR: 'MMS_CREATE_VENDOR',
  LIST_VENDOR: 'MMS_LIST_VENDOR',
  DETAIL_VENDOR: 'MMS_DETAIL_VENDOR',
  UPDATE_VENDOR: 'MMS_UPDATE_VENDOR',
  UPDATE_STATUS_VENDOR: 'MMS_UPDATE_STATUS_VENDOR',
  IMPORT_VENDOR: 'MMS_IMPORT_VENDOR',
  EXPORT_VENDOR: 'MMS_EXPORT_VENDOR',

  // WAREHOUSE_EXPORT_GROUP
  CREATE_WAREHOUSE_EXPORT: 'MMS_CREATE_WAREHOUSE_EXPORT',
  UPDATE_WAREHOUSE_EXPORT: 'MMS_UPDATE_WAREHOUSE_EXPORT',
  DETAIL_WAREHOUSE_EXPORT: 'MMS_DETAIL_WAREHOUSE_EXPORT',
  LIST_WAREHOUSE_EXPORT: 'MMS_LIST_WAREHOUSE_EXPORT',
  CONFIRM_WAREHOUSE_EXPORT: 'MMS_CONFIRM_WAREHOUSE_EXPORT',
  DELETE_WAREHOUSE_EXPORT: 'MMS_DELETE_WAREHOUSE_EXPORT',
  UPDATE_STATUS_WAREHOUSE_EXPORT: 'MMS_UPDATE_STATUS_WAREHOUSE_EXPORT',
  IMPORT_WAREHOUSE_EXPORT: 'MMS_IMPORT_WAREHOUSE_EXPORT',
  EXPORT_WAREHOUSE_EXPORT: 'MMS_EXPORT_WAREHOUSE_EXPORT',
  DEVICE_WAREHOUSE_EXPORT: 'MMS_DEVICE_WAREHOUSE_EXPORT',
  SUPPLY_WAREHOUSE_EXPORT: 'MMS_SUPPLY_WAREHOUSE_EXPORT',

  // WAREHOUSE_IMPORT_GROUP
  CREATE_WAREHOUSE_IMPORT: 'MMS_CREATE_WAREHOUSE_IMPORT',
  UPDATE_WAREHOUSE_IMPORT: 'MMS_UPDATE_WAREHOUSE_IMPORT',
  DETAIL_WAREHOUSE_IMPORT: 'MMS_DETAIL_WAREHOUSE_IMPORT',
  LIST_WAREHOUSE_IMPORT: 'MMS_LIST_WAREHOUSE_IMPORT',
  CONFIRM_WAREHOUSE_IMPORT: 'MMS_CONFIRM_WAREHOUSE_IMPORT',
  UPDATE_STATUS_WAREHOUSE_IMPORT: 'MMS_UPDATE_STATUS_WAREHOUSE_IMPORT',
  DELETE_WAREHOUSE_IMPORT: 'MMS_DELETE_WAREHOUSE_IMPORT',
  IMPORT_WAREHOUSE_IMPORT: 'MMS_IMPORT_WAREHOUSE_IMPORT',
  EXPORT_WAREHOUSE_IMPORT: 'MMS_EXPORT_WAREHOUSE_IMPORT',
  DEVICE_WAREHOUSE_IMPORT: 'MMS_DEVICE_WAREHOUSE_IMPORT',
  SUPPLY_WAREHOUSE_IMPORT: 'MMS_SUPPLY_WAREHOUSE_IMPORT',

  // WAREHOUSE_INVENTORY_GROUP
  LIST_WAREHOUSE_INVENTORY: 'MMS_LIST_WAREHOUSE_INVENTORY',
  LIST_INVENTORY_SUPPLY: 'MMS_LIST_INVENTORY_SUPPLY',
  LIST_INVENTORY_DEVICE_GROUP: 'MMS_LIST_INVENTORY_DEVICE_GROUP',
  DETAIL_INVENTORY_DEVICE_GROUP: 'MMS_DETAIL_INVENTORY_DEVICE_GROUP',
  EXPORT_INVENTORY_SUPPLY: 'MMS_EXPORT_INVENTORY_SUPPLY',
  EXPORT_INVENTORY_DEVICE_GROUP: 'MMS_EXPORT_INVENTORY_DEVICE_GROUP',
  EXPORT_DEVICE_INVENTORY: 'MMS_EXPORT_DEVICE_INVENTORY',

  // WAREHOUSE_GROUP
  CREATE_WAREHOUSE: 'MMS_CREATE_WAREHOUSE',
  UPDATE_WAREHOUSE: 'MMS_UPDATE_WAREHOUSE',
  DETAIL_WAREHOUSE: 'MMS_DETAIL_WAREHOUSE',
  LIST_WAREHOUSE: 'MMS_LIST_WAREHOUSE',
  IMPORT_WAREHOUSE: 'MMS_IMPORT_WAREHOUSE',
  EXPORT_WAREHOUSE: 'MMS_EXPORT_WAREHOUSE',

  // WARNING_GROUP
  DETAIL_WARNING: 'MMS_DETAIL_WARNING',
  LIST_WARNING: 'MMS_LIST_WARNING',
  UPDATE_STATUS_WARNING: 'MMS_UPDATE_STATUS_WARNING',

  // FACTORY_GROUP
  CREATE_FACTORY: 'USER_CREATE_FACTORY',
  UPDATE_FACTORY: 'USER_UPDATE_FACTORY',
  DELETE_FACTORY: 'USER_DELETE_FACTORY',
  DETAIL_FACTORY: 'USER_DETAIL_FACTORY',
  LIST_FACTORY: 'USER_LIST_FACTORY',
  CONFIRM_FACTORY: 'USER_CONFIRM_FACTORY',
  REJECT_FACTORY: 'USER_REJECT_FACTORY',
  IMPORT_FACTORY: 'USER_IMPORT_FACTORY',
  EXPORT_FACTORY: 'USER_EXPORT_FACTORY',
  UDPATE_MANY_STATUS_FACTORY: 'USER_UDPATE_MANY_STATUS_FACTORY',
  UPDATE_STATUS_FACTORY: 'USER_UPDATE_STATUS_FACTORY',

  // COMPANY_GROUP
  CREATE_COMPANY: 'USER_CREATE_COMPANY',
  UPDATE_COMPANY: 'USER_UPDATE_COMPANY',
  UPDATE_STATUS_COMPANY: 'USER_UPDATE_STATUS_COMPANY',
  DELETE_COMPANY: 'USER_DELETE_COMPANY',
  DETAIL_COMPANY: 'USER_DETAIL_COMPANY',
  LIST_COMPANY: 'USER_LIST_COMPANY',
  CONFIRM_COMPANY: 'USER_CONFIRM_COMPANY',
  REJECT_COMPANY: 'USER_REJECT_COMPANY',
  IMPORT_COMPANY: 'USER_IMPORT_COMPANY',
  EXPORT_COMPANY: 'USER_EXPORT_COMPANY',

  // PERMISSION_GROUP
  SET_PERMISSION_USER: 'USER_SET_PERMISSION_USER',
  LIST_PERMISSION_USER: 'USER_LIST_PERMISSION_USER',

  // DEPARTMENT_GROUP
  CREATE_DEPARTMENT: 'USER_CREATE_DEPARTMENT',
  UPDATE_DEPARTMENT: 'USER_UPDATE_DEPARTMENT',
  DETAIL_DEPARTMENT: 'USER_DETAIL_DEPARTMENT',
  LIST_DEPARTMENT: 'USER_LIST_DEPARTMENT',
  UPDATE_STATUS_DEPARTMENT: 'USER_UPDATE_STATUS_DEPARTMENT',
  PERMISSION_DEPARTMENT: 'USER_PERMISSION_DEPARTMENT',

  // ROLE_GROUP
  CREATE_ROLE: 'USER_CREATE_ROLE',
  DETAIL_ROLE: 'USER_DETAIL_ROLE',
  UPDATE_ROLE: 'USER_UPDATE_ROLE',
  LIST_ROLE: 'USER_LIST_ROLE',
  UPDATE_STATUS_ROLE: 'USER_UPDATE_STATUS_ROLE',

  // USER_GROUP
  CREATE_USER: 'USER_CREATE_USER',
  UPDATE_USER: 'USER_UPDATE_USER',
  DETAIL_USER: 'USER_DETAIL_USER',
  LIST_USER: 'USER_LIST_USER',
  CHANGE_PASSWORD_USER: 'USER_CHANGE_PASSWORD_USER',
  EXPORT_USER: 'USER_EXPORT_USER',
  UPDATE_STATUS_USER: 'USER_UPDATE_STATUS_USER',

  // REPORT_DEVICE_STATUS_GROUP
  SYNTHESIS_REPORT_DEVICE_STATUS: 'MMS_SYNTHESIS_REPORT_DEVICE_STATUS',
  DETAIL_REPORT_DEVICE_STATUS: 'MMS_DETAIL_REPORT_DEVICE_STATUS',
  EXPORT_SYNTHESIS_REPORT_DEVICE_STATUS:
    'MMS_EXPORT_SYNTHESIS_REPORT_DEVICE_STATUS',
  EXPORT_DETAIL_REPORT_DEVICE_STATUS: 'MMS_EXPORT_DETAIL_REPORT_DEVICE_STATUS',

  // REPORT_DEVICE_MAINTENANCE_GROUP
  REPORT_LIST_DEVICE_MAINTENANCE_PERMISSION:
    'MMS_REPORT_LIST_DEVICE_MAINTENANCE_PERMISSION',
  EXPORT_REPORT_DEVICE_MAINTENANCE: 'MMS_EXPORT_REPORT_DEVICE_MAINTENANCE',

  // REPORT_DEVICE_TRANSFER_GROUP
  REPORT_LIST_DEVICE_TRANSFER: 'MMS_REPORT_LIST_DEVICE_TRANSFER',
  REPORT_DETAIL_DEVICE_TRANSFER: 'MMS_REPORT_DETAIL_DEVICE_TRANSFER',
  EXPORT_REPORT_DEVICE_TRANSFER: 'MMS_EXPORT_REPORT_DEVICE_TRANSFER',
  EXPORT_REPORT_DETAIL_DEVICE_TRANSFER:
    'MMS_EXPORT_REPORT_DETAIL_DEVICE_TRANSFER',

  // REPORT_DEVICE_GROUP
  REPORT_LIST_DEVICE_SYNTHESIS: 'MMS_REPORT_LIST_DEVICE_SYNTHESIS',
  EXPORT_REPORT_DEVICE_SYNTHESIS: 'MMS_EXPORT_REPORT_DEVICE_SYNTHESIS',

  // REPORT_NEW_INVESTMENT_DEVICE
  REPORT_NEW_INVESTMENT_DEVICE: 'MMS_REPORT_NEW_INVESTMENT_DEVICE',
  EXPORT_REPORT_NEW_INVESTMENT_DEVICE:
    'MMS_EXPORT_REPORT_NEW_INVESTMENT_DEVICE',

  // UPDATE_INVENTORY_GROUP
  CREATE_UPDATE_INVENTORY: 'MMS_CREATE_UPDATE_INVENTORY',
  UPDATE_UPDATE_INVENTORY: 'MMS_UPDATE_UPDATE_INVENTORY',
  UPDATE_STATUS_UPDATE_INVENTORY: 'MMS_UPDATE_STATUS_UPDATE_INVENTORY',
  DELETE_UPDATE_INVENTORY: 'MMS_DELETE_UPDATE_INVENTORY',
  LIST_UPDATE_INVENTORY: 'MMS_LIST_UPDATE_INVENTORY',
  DETAIL_UPDATE_INVENTORY: 'MMS_DETAIL_UPDATE_INVENTORY',

  // OPERATION_VALUE_GROUP
  CREATE_OPERATION_VALUE: 'MMS_CREATE_OPERATION_VALUE',
  LIST_OPERATION_VALUE: 'MMS_LIST_OPERATION_VALUE',
  DETAIL_OPERATION_VALUE: 'MMS_DETAIL_OPERATION_VALUE',
  UPDATE_OPERATION_VALUE: 'MMS_UPDATE_OPERATION_VALUE',
  EXPORT_OPERATION_VALUE: 'MMS_EXPORT_OPERATION_VALUE',

  // WAREHOUSE_EXPORT_REQUEST_GROUP
  CREATE_WAREHOUSE_EXPORT_REQUEST: 'MMS_CREATE_WAREHOUSE_EXPORT_REQUEST',
  DELETE_WAREHOUSE_EXPORT_REQUEST: 'MMS_DELETE_WAREHOUSE_EXPORT_REQUEST',
  DEVICE_WAREHOUSE_EXPORT_REQUEST: 'MMS_DEVICE_WAREHOUSE_EXPORT_REQUEST',
  SUPPLY_WAREHOUSE_EXPORT_REQUEST: 'MMS_SUPPLY_WAREHOUSE_EXPORT_REQUEST',
  UPDATE_WAREHOUSE_EXPORT_REQUEST: 'MMS_UPDATE_WAREHOUSE_EXPORT_REQUEST',
  DETAIL_WAREHOUSE_EXPORT_REQUEST: 'MMS_DETAIL_WAREHOUSE_EXPORT_REQUEST',
  LIST_WAREHOUSE_EXPORT_REQUEST: 'MMS_LIST_WAREHOUSE_EXPORT_REQUEST',
  UPDATE_STATUS_WAREHOUSE_EXPORT_REQUEST:
    'MMS_UPDATE_STATUS_WAREHOUSE_EXPORT_REQUEST',

  // WAREHOUSE_IMPORT_REQUEST_GROUP
  CREATE_WAREHOUSE_IMPORT_REQUEST: 'MMS_CREATE_WAREHOUSE_IMPORT_REQUEST',
  UPDATE_WAREHOUSE_IMPORT_REQUEST: 'MMS_UPDATE_WAREHOUSE_IMPORT_REQUEST',
  DETAIL_WAREHOUSE_IMPORT_REQUEST: 'MMS_DETAIL_WAREHOUSE_IMPORT_REQUEST',
  LIST_WAREHOUSE_IMPORT_REQUEST: 'MMS_LIST_WAREHOUSE_IMPORT_REQUEST',
  UPDATE_STATUS_WAREHOUSE_IMPORT_REQUEST:
    'MMS_UPDATE_STATUS_WAREHOUSE_IMPORT_REQUEST',
  DELETE_WAREHOUSE_IMPORT_REQUEST: 'MMS_DELETE_WAREHOUSE_IMPORT_REQUEST',
  DEVICE_WAREHOUSE_IMPORT_REQUEST: 'MMS_DEVICE_WAREHOUSE_IMPORT_REQUEST',
  SUPPLY_WAREHOUSE_IMPORT_REQUEST: 'MMS_SUPPLY_WAREHOUSE_IMPORT_REQUEST',
}
